# Workflow for running things with poetry - without docker
name: Poetry
on: push

jobs:
  Poetry:
    name: poetry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v2

      - name: Install
        run: poetry install
      - name: Pytest
        run: |
          poetry run pytest -v \
          --cov=all_tools \
          --cov-report term-missing:skip-covered \
          --doctest-modules
      - name: Black
        run: poetry run black all_tools
      - name: Vulture
        run: poetry run vulture all_tools
      - name: Pylint
        run: |
          poetry run pylint all_tools \
          --output-format=colorized \
          --reports=y
      - name: Wily
        run: |
          poetry run wily build all_tools/; wily diff all_tools/ -r HEAD^1
